### ISSUE TITLE
No puedo procesar el pago en mi tienda woocommerce con openpay

### ISSUE THREAD

**Issue by elPonchoHB86** [open-pay/openpay-woocommerce#116]
Hola, tengo instalado en mi pagina wordpress woocommerce y openpay para los pagos con tarjeta, el problema es que no puedo procesar el pago en modo sandbox, a veces obtengo un mensaje vacio de esta manera (esto cuando estoy logueado como administrador):

![image](https://github.com/open-pay/openpay-woocommerce/assets/136853755/ce28aae2-23af-4b33-879d-e037c02e08eb)

y cuando intento procesar el pago como un cliente obtengo este otro mensaje:

![image](https://github.com/open-pay/openpay-woocommerce/assets/136853755/25193f86-385f-48ad-a883-159c12b38ad5)

ya intente de muchas formas y no puedo lograr procesar el pago, hay algo que me este faltando hacer?

agradezco mucho si alguien me pudiera ayudar con esto

**Comment by abundis-rmn2** [comment]
Tengo el mismo error, estaba funcionando, pero actualmente da el siguiente error:

`2023-08-23T00:43:30+00:00 CRITICAL Uncaught Error: Call to a member function create() on null in /var/www/html/shop/new/nutrapel_2/wp-content/plugins/openpay-cards/openpay_cards_gateway.php:663
Stack trace:
#0 /var/www/html/shop/new/nutrapel_2/wp-content/plugins/openpay-cards/openpay_cards_gateway.php(631): Openpay_Cards->createOpenpayCharge(false, Array, 'https://tienda....')
#1 /var/www/html/shop/new/nutrapel_2/wp-content/plugins/openpay-cards/openpay_cards_gateway.php(542): Openpay_Cards->processOpenpayCharge('zdufLId60JHfa3t...', 'krplcmi3b3hvlms...', '1', 'false', 'new', false, NULL)
#2 /var/www/html/shop/new/nutrapel_2/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1050): Openpay_Cards->process_payment(24167)
#3 /var/www/html/shop/new/nutrapel_2/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1279): WC_Checkout->process_order_payment(24167, 'openpay_cards')
#4 /var/www/html/shop/new/nutrapel_2/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(481): WC_Checkout->process_checkout()
#5 /var/www/html/shop en /var/www/html/shop/new/nutrapel_2/wp-content/plugins/openpay-cards/openpay_cards_gateway.php en la línea 663`

**Comment by JGTI** [comment]
Te dejo la solución 
remplaza este archivo en /wp-content/plugins/openpay-cards/openpay_cards_gateway.php 
https://github.com/JGTI/openpay-wordpress-solucion/blob/main/openpay_cards_gateway.php

**Comment by econopapi** [comment]
¿Alguien sabe si se le dio solución? En pleno 2026 el plugin sigue sin funcionar, y soporte técnico nomás no da una.
